### ISSUE TITLE
Live seems broken

### ISSUE THREAD

**Issue by doctornkz** [darksky83/plugin.video.tviplayer#3]
```
20:38:57 8618.230469 T:1964044288   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
20:38:57 8618.534180 T:1757172640  NOTICE: TVI-KODI-PLAYER Mode: 40015   URL: http://tviplayer.iol.pt  Name: Direct  IconImage: None
20:38:59 8619.937500 T:1757172640  NOTICE: TVI-KODI-PLAYER Mode: 20   URL: http://tviplayer.iol.pt/direto/TVI24  Name: TVI 24  IconImage: None
20:39:00 8620.666992 T:1757172640  NOTICE: Session: None
20:39:00 8620.669922 T:1757172640  NOTICE: WMS ID: wmsAuthSign=c2VydmVyX3RpbWU9My8zLzIwMTggNTozODo1OSBQTSZoYXNoX3ZhbHVlPW1kYXQrdzUvZ0lVa3NpeE5ScHFBMHc9PSZ2YWxpZG1pbnV0ZXM9MTQ0MCZpZD0wMzljM2RiYi0wNzMyLTRlNjMtOWZkNS0yZjhlMjM2N2JiZTY
20:39:00 8620.672852 T:1757172640  NOTICE: Balancer host: https://video-auth8.iol.pt/live_tvi24/live_tvi24/playlist.m3u8
20:39:00 8620.674805 T:1757172640  NOTICE: Playlist URL:https://video-auth8.iol.pt/live_tvi24/live_tvi24/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9My8zLzIwMTggNTozODo1OSBQTSZoYXNoX3ZhbHVlPW1kYXQrdzUvZ0lVa3NpeE5ScHFBMHc9PSZ2YWxpZG1pbnV0ZXM9MTQ0MCZpZD0wMzljM2RiYi0wNzMyLTRlNjMtOWZkNS0yZjhlMjM2N2JiZTY
20:39:00 8621.574219 T:1757172640  NOTICE: abrir_url fail =https://video-auth8.iol.pt/live_tvi24/live_tvi24/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9My8zLzIwMTggNTozODo1OSBQTSZoYXNoX3ZhbHVlPW1kYXQrdzUvZ0lVa3NpeE5ScHFBMHc9PSZ2YWxpZG1pbnV0ZXM9MTQ0MCZpZD0wMzljM2RiYi0wNzMyLTRlNjMtOWZkNS0yZjhlMjM2N2JiZTY
20:39:00 8621.578125 T:1757172640   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.tviplayer/addon.py", line 173, in <module>
                                                get_show_direto(name, url, iconimage)
                                              File "/storage/.kodi/addons/plugin.video.tviplayer/resources/ondemand.py", line 306, in get_show_direto
                                                url = url_short + chunks_array[quality]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--

```

**Comment by doctornkz** [comment]
Assign it on me, plz.

**Comment by darksky83** [comment]
Hi 
You can make a pull request, but please try to not reformat the files that makes it very hard to review :)

Thanks for the help 👍
